# Generated by Django 3.2 on 2022-03-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='device_id',
        ),
    ]
